name: Auto Clean ImageCI

on:
  schedule:
    # once for a week
    - cron: "0 0 * * 0"

jobs:
  prune-daemon-ci:
    uses: ./.github/workflows/call-clean-ghcr.yaml
    with:
      image_name: daemon
      older_than: "2"
    secrets: inherit
