name: Call Release Plesase

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/install-go


      - name: Build Binary
        run: |
          GOARCH=${{ matrix.arch }} make build-bin install-bin

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: zip
          filename: kcrow-linux-${{ matrix.arch }}.zip
          path: ./output/${{ matrix.arch }}/bin/

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kcrow-linux-${{ matrix.arch }}.zip
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

          